extends: default

rules:
  # Align with ansible-lint required yaml rules
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  # Project-specific preferences
  line-length:
    max: 180
    level: warning
  truthy: disable
  document-start: disable
