---
- name: Install dependencies
  ansible.builtin.apt:
    pkg: ["libssl-dev", "libudev-dev", "pkg-config", "zlib1g-dev", "llvm", "clang", "make", "git", "acl", "protobuf-compiler"]
    state: present

- name: Install linux kernel tools
  ansible.builtin.apt:
    pkg: ["linux-tools-generic", "linux-tools-{{ ansible_kernel }}", "inotify-tools", "htop", "iotop", "powertop", "cpufrequtils"]
    state: present
