---
- name: Install build and system dependencies
  ansible.builtin.apt:
    pkg:
      - libssl-dev
      - libudev-dev
      - pkg-config
      - zlib1g-dev
      - llvm
      - clang
      - make
      - git
      - acl
      - protobuf-compiler
    state: present

- name: Install kernel tools (Ubuntu)
  ansible.builtin.apt:
    pkg:
      - linux-tools-generic
      - linux-tools-{{ ansible_kernel }}
      - inotify-tools
      - htop
      - iotop
      - powertop
      - cpufrequtils
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install kernel tools (Debian)
  ansible.builtin.apt:
    pkg:
      - linux-perf
      - inotify-tools
      - htop
      - iotop
      - powertop
      - cpufrequtils
    state: present
  when: ansible_distribution == 'Debian'
